name: Build OpenTTD-nice
on: [push, pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@b5ebd11c5dfe515aeafcad2c8e8f066b3017690c
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGtest
          OUTDIR: $HOME/arch-packages
      - name: move file
        run: |
          mkdir -p ./artifact/
          find $HOME/arch-packages -type f -name "*.zst*"
          cp -rf $(find $HOME/arch-packages -type f -name "*.zst*") ./artifact/
      - name: Upload package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: ./artifact/
