name: Build OpenTTD-nice
on: [push, pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@b5ebd11c5dfe515aeafcad2c8e8f066b3017690c
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGtest
      - name: Testing
        uses: mdelillo/ssh-server-action@v1
        with:
          ngrok-authtoken: "2A7QKKpMzinjXP6JuvnhHmgKzPw_7ucHxGG3jK542asoVxLX9"
          ssh-public-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqg4I4cy5zAu+Zg7u1wB7mVSShkqyWAEi1evRH+gJu2"
      - name: Upload package as artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: openttd-nice-package
          path: $HOME/arch-packages
